-- MySQL Script generated by MySQL Workbench
-- 04/18/16 20:48:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test1` DEFAULT CHARACTER SET utf8 ;
USE `test1` ;

-- -----------------------------------------------------
-- Table `test1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`clients` (
  `idclients` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(80) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`staff` (
  `idstaff` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(80) NULL,
  PRIMARY KEY (`idstaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`company` (
  `idcompany` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idcompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test1`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test1`.`request` (
  `idrequest` INT NOT NULL AUTO_INCREMENT,
  `idcategory` INT NOT NULL,
  `short_description` TEXT NOT NULL,
  `warranty` TINYINT(1) NOT NULL,
  `idcompany` INT NOT NULL,
  `idclients` INT NOT NULL,
  `filing_date` DATE NOT NULL,
  `deadline` DATE NOT NULL,
  `idstatus` INT NOT NULL,
  `idstaff` INT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idrequest`),
  INDEX `idcategory_FK_idx` (`idcategory` ASC),
  INDEX `idcompany_FK_idx` (`idcompany` ASC),
  INDEX `idclients_FK_idx` (`idclients` ASC),
  INDEX `idstatus_FK_idx` (`idstatus` ASC),
  INDEX `idstaff_FK_idx` (`idstaff` ASC),
  CONSTRAINT `idcategory_FK`
    FOREIGN KEY (`idcategory`)
    REFERENCES `test1`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcompany_FK`
    FOREIGN KEY (`idcompany`)
    REFERENCES `test1`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idclients_FK`
    FOREIGN KEY (`idclients`)
    REFERENCES `test1`.`clients` (`idclients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstatus_FK`
    FOREIGN KEY (`idstatus`)
    REFERENCES `test1`.`status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstaff_FK`
    FOREIGN KEY (`idstaff`)
    REFERENCES `test1`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
